### ISSUE TITLE
ServiceConnection disconnect throws exception

### ISSUE THREAD

**Issue by cmucha** [DocuWare/PlatformJavaClient#9] opened 2017-06-27 11:31 UTC
ServiceConnection disconnect throws exception:
"A message body reader for Java class com.sun.jersey.api.client.ClientResponse, and Java type class com.sun.jersey.api.client.ClientResponse, and MIME media type application/xml; charset=utf-8 was not found"

more detailed:
Jun 27, 2017 1:24:57 PM com.sun.jersey.api.client.ClientResponse getEntity
SCHWERWIEGEND: A message body reader for Java class com.sun.jersey.api.client.ClientResponse, and Java type class com.sun.jersey.api.client.ClientResponse, and MIME media type application/xml; charset=utf-8 was not found
Jun 27, 2017 1:24:57 PM com.sun.jersey.api.client.ClientResponse getEntity
SCHWERWIEGEND: The registered message body readers compatible with the MIME media type are:
application/xml; charset=utf-8 ->
  com.sun.jersey.core.impl.provider.entity.XMLJAXBElementProvider$App
  com.sun.jersey.core.impl.provider.entity.DocumentProvider
  com.sun.jersey.core.impl.provider.entity.SourceProvider$StreamSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$SAXSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$DOMSourceReader
  com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$App
  com.sun.jersey.core.impl.provider.entity.XMLListElementProvider$App
  com.sun.jersey.core.impl.provider.entity.XMLRootObjectProvider$App
*/* ->
  com.sun.jersey.core.impl.provider.entity.FormProvider
  com.sun.jersey.core.impl.provider.entity.StringProvider
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.XMLJAXBElementProvider$General
  com.sun.jersey.core.impl.provider.entity.ReaderProvider
  com.sun.jersey.core.impl.provider.entity.DocumentProvider
  com.sun.jersey.core.impl.provider.entity.SourceProvider$StreamSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$SAXSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$DOMSourceReader
  com.sun.jersey.json.impl.provider.entity.JSONJAXBElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLListElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLRootObjectProvider$General
  com.sun.jersey.core.impl.provider.entity.EntityHolderReader
  com.sun.jersey.json.impl.provider.entity.JSONRootElementProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONListElementProvider$General

**Comment by GranatenUdo** [comment] 2017-06-27 14:56
which version of DocuWare is your client talking to?

**Update:** I was able to reproduce the issue with 6.11. Added Bug Tag.

**Comment by cmucha** [comment] 2017-06-28 06:23
I get the exception with every version i tested:
6.7, 6.8, 6.9, 6.10, 6.11

**Comment by GranatenUdo** [comment] 2017-06-28 15:58
the problem is fixed with the following commit! thanks for reporting 👍 

[https://github.com/DocuWare/PlatformJavaClient/commit/5263fa03e4143a79ae3be37ad3c47ea2ebb6508c](url)

**Closed as completed by GranatenUdo** 2017-06-28 15:58 UTC
Labels: bug
